  stock_pantry_pepsi_max:
    name: pepsi max
    min: 0
    max: 1000
    step: 1
  stock_pantry_costco_water:
    name: costco water
    min: 0
    max: 1000
    step: 1
  stock_pantry_highland_spring_water:
    name: highland spring water
    min: 0
    max: 1000
    step: 1
  stock_pantry_fanta:
    name: fanta
    min: 0
    max: 1000
    step: 1
  stock_pantry_fresh_oj:
    name: fresh oj
    min: 0
    max: 1000
    step: 1
  stock_pantry_summer_fruits:
    name: summer fruits
    min: 0
    max: 1000
    step: 1
